"""empty message

Revision ID: 2aaeaf7e3390
Revises: ee5859411e86
Create Date: 2021-07-22 14:37:35.286358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaeaf7e3390'
down_revision = 'ee5859411e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
